ALTER TABLE cabors
ADD COLUMN kategori VARCHAR(50) DEFAULT '',
ADD COLUMN total_medali INTEGER DEFAULT 0,
ADD COLUMN technical_delegate VARCHAR(100) DEFAULT '',
ADD COLUMN status VARCHAR(20) DEFAULT 'Aktif';
