// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountOtherActiveSuperAdmins(ctx context.Context, id pgtype.UUID) (int64, error)
	CountUsersPage(ctx context.Context, arg CountUsersPageParams) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, arg DeleteUserParams) error
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByKeycloakID(ctx context.Context, keycloakID string) (User, error)
	ListUsers(ctx context.Context) ([]User, error)
	ListUsersPage(ctx context.Context, arg ListUsersPageParams) ([]User, error)
	RestoreUser(ctx context.Context, arg RestoreUserParams) (User, error)
	SetUserStatus(ctx context.Context, arg SetUserStatusParams) (User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
