// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Match struct {
	ID             pgtype.UUID `json:"id"`
	NomorTandingID pgtype.UUID `json:"nomor_tanding_id"`
	// External UUID owned by venue-service; validated through the service contract.
	VenueID      pgtype.UUID        `json:"venue_id"`
	MatchDate    pgtype.Timestamptz `json:"match_date"`
	Status       string             `json:"status"`
	Round        string             `json:"round"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy    pgtype.Text        `json:"deleted_by"`
	DeleteReason pgtype.Text        `json:"delete_reason"`
}

type MatchParticipant struct {
	ID           pgtype.UUID        `json:"id"`
	MatchID      pgtype.UUID        `json:"match_id"`
	KontingenID  pgtype.UUID        `json:"kontingen_id"`
	AthleteName  pgtype.Text        `json:"athlete_name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy    pgtype.Text        `json:"deleted_by"`
	DeleteReason pgtype.Text        `json:"delete_reason"`
}

type Venue struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Address      pgtype.Text        `json:"address"`
	Capacity     pgtype.Int4        `json:"capacity"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	City         string             `json:"city"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy    pgtype.Text        `json:"deleted_by"`
	DeleteReason pgtype.Text        `json:"delete_reason"`
}
