// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddMatchParticipant(ctx context.Context, arg AddMatchParticipantParams) (MatchParticipant, error)
	CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error)
	CreateVenue(ctx context.Context, arg CreateVenueParams) (Venue, error)
	GetMatchByID(ctx context.Context, id pgtype.UUID) (Match, error)
	GetVenueByID(ctx context.Context, id pgtype.UUID) (Venue, error)
	ListMatchParticipants(ctx context.Context, matchID pgtype.UUID) ([]MatchParticipant, error)
	ListMatches(ctx context.Context) ([]Match, error)
	ListVenues(ctx context.Context, dollar_1 string) ([]Venue, error)
	SoftDeleteMatchParticipants(ctx context.Context, arg SoftDeleteMatchParticipantsParams) error
	UpdateMatch(ctx context.Context, arg UpdateMatchParams) (Match, error)
	UpdateVenue(ctx context.Context, arg UpdateVenueParams) (Venue, error)
}

var _ Querier = (*Queries)(nil)
