// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMatchParticipant = `-- name: AddMatchParticipant :one
INSERT INTO match_participants (match_id, kontingen_id, participant_type, athlete_name, team_name, slot)
VALUES (
  $1,
  $2,
  $3,
  NULLIF(BTRIM($4::text), ''),
  NULLIF(BTRIM($5::text), ''),
  $6
)
RETURNING id, match_id, kontingen_id, athlete_name, created_at, updated_at, deleted_at, deleted_by, delete_reason, participant_type, team_name, slot
`

type AddMatchParticipantParams struct {
	MatchID         pgtype.UUID `json:"match_id"`
	KontingenID     pgtype.UUID `json:"kontingen_id"`
	ParticipantType string      `json:"participant_type"`
	AthleteName     string      `json:"athlete_name"`
	TeamName        string      `json:"team_name"`
	Slot            int16       `json:"slot"`
}

func (q *Queries) AddMatchParticipant(ctx context.Context, arg AddMatchParticipantParams) (MatchParticipant, error) {
	row := q.db.QueryRow(ctx, addMatchParticipant,
		arg.MatchID,
		arg.KontingenID,
		arg.ParticipantType,
		arg.AthleteName,
		arg.TeamName,
		arg.Slot,
	)
	var i MatchParticipant
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.KontingenID,
		&i.AthleteName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.DeleteReason,
		&i.ParticipantType,
		&i.TeamName,
		&i.Slot,
	)
	return i, err
}

const createMatch = `-- name: CreateMatch :one
INSERT INTO matches (nomor_tanding_id, venue_id, match_date, status, round)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, nomor_tanding_id, venue_id, match_date, status, round, created_at, updated_at, deleted_at, deleted_by, delete_reason
`

type CreateMatchParams struct {
	NomorTandingID pgtype.UUID        `json:"nomor_tanding_id"`
	VenueID        pgtype.UUID        `json:"venue_id"`
	MatchDate      pgtype.Timestamptz `json:"match_date"`
	Status         string             `json:"status"`
	Round          string             `json:"round"`
}

func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, createMatch,
		arg.NomorTandingID,
		arg.VenueID,
		arg.MatchDate,
		arg.Status,
		arg.Round,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.NomorTandingID,
		&i.VenueID,
		&i.MatchDate,
		&i.Status,
		&i.Round,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.DeleteReason,
	)
	return i, err
}

const createVenue = `-- name: CreateVenue :one
INSERT INTO venues (name, address, capacity, city)
VALUES ($1, $2, $3, $4)
RETURNING id, name, address, capacity, created_at, updated_at, city, deleted_at, deleted_by, delete_reason
`

type CreateVenueParams struct {
	Name     string      `json:"name"`
	Address  pgtype.Text `json:"address"`
	Capacity pgtype.Int4 `json:"capacity"`
	City     string      `json:"city"`
}

func (q *Queries) CreateVenue(ctx context.Context, arg CreateVenueParams) (Venue, error) {
	row := q.db.QueryRow(ctx, createVenue,
		arg.Name,
		arg.Address,
		arg.Capacity,
		arg.City,
	)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.City,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.DeleteReason,
	)
	return i, err
}

const getMatchByID = `-- name: GetMatchByID :one
SELECT id, nomor_tanding_id, venue_id, match_date, status, round, created_at, updated_at, deleted_at, deleted_by, delete_reason FROM matches WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetMatchByID(ctx context.Context, id pgtype.UUID) (Match, error) {
	row := q.db.QueryRow(ctx, getMatchByID, id)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.NomorTandingID,
		&i.VenueID,
		&i.MatchDate,
		&i.Status,
		&i.Round,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.DeleteReason,
	)
	return i, err
}

const getVenueByID = `-- name: GetVenueByID :one
SELECT id, name, address, capacity, created_at, updated_at, city, deleted_at, deleted_by, delete_reason FROM venues WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetVenueByID(ctx context.Context, id pgtype.UUID) (Venue, error) {
	row := q.db.QueryRow(ctx, getVenueByID, id)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.City,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.DeleteReason,
	)
	return i, err
}

const listMatchParticipants = `-- name: ListMatchParticipants :many
SELECT id, match_id, kontingen_id, athlete_name, created_at, updated_at, deleted_at, deleted_by, delete_reason, participant_type, team_name, slot FROM match_participants
WHERE match_id = $1 AND deleted_at IS NULL
ORDER BY slot ASC, created_at ASC
`

func (q *Queries) ListMatchParticipants(ctx context.Context, matchID pgtype.UUID) ([]MatchParticipant, error) {
	rows, err := q.db.Query(ctx, listMatchParticipants, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MatchParticipant
	for rows.Next() {
		var i MatchParticipant
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.KontingenID,
			&i.AthleteName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.DeleteReason,
			&i.ParticipantType,
			&i.TeamName,
			&i.Slot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatches = `-- name: ListMatches :many
SELECT id, nomor_tanding_id, venue_id, match_date, status, round, created_at, updated_at, deleted_at, deleted_by, delete_reason FROM matches
WHERE deleted_at IS NULL
ORDER BY match_date ASC
`

func (q *Queries) ListMatches(ctx context.Context) ([]Match, error) {
	rows, err := q.db.Query(ctx, listMatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Match
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.NomorTandingID,
			&i.VenueID,
			&i.MatchDate,
			&i.Status,
			&i.Round,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.DeleteReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVenues = `-- name: ListVenues :many
SELECT id, name, address, capacity, created_at, updated_at, city, deleted_at, deleted_by, delete_reason FROM venues
WHERE deleted_at IS NULL
  AND city = COALESCE(NULLIF($1::text, ''), city)
ORDER BY name ASC
`

func (q *Queries) ListVenues(ctx context.Context, dollar_1 string) ([]Venue, error) {
	rows, err := q.db.Query(ctx, listVenues, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Venue
	for rows.Next() {
		var i Venue
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Capacity,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.City,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.DeleteReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteMatchParticipants = `-- name: SoftDeleteMatchParticipants :exec
UPDATE match_participants
SET deleted_at = NOW(),
    deleted_by = $1,
    delete_reason = $2,
    updated_at = NOW()
WHERE match_id = $3
  AND deleted_at IS NULL
`

type SoftDeleteMatchParticipantsParams struct {
	DeletedBy    pgtype.Text `json:"deleted_by"`
	DeleteReason pgtype.Text `json:"delete_reason"`
	MatchID      pgtype.UUID `json:"match_id"`
}

func (q *Queries) SoftDeleteMatchParticipants(ctx context.Context, arg SoftDeleteMatchParticipantsParams) error {
	_, err := q.db.Exec(ctx, softDeleteMatchParticipants, arg.DeletedBy, arg.DeleteReason, arg.MatchID)
	return err
}

const updateMatch = `-- name: UpdateMatch :one
UPDATE matches
SET 
  nomor_tanding_id = COALESCE(NULLIF($2::uuid, '00000000-0000-0000-0000-000000000000'::uuid), nomor_tanding_id),
  venue_id = COALESCE(NULLIF($3::uuid, '00000000-0000-0000-0000-000000000000'::uuid), venue_id),
  match_date = COALESCE(NULLIF($4::timestamptz, '0001-01-01 00:00:00Z'::timestamptz), match_date),
  status = COALESCE(NULLIF($5::text, ''), status),
  round = COALESCE(NULLIF($6::text, ''), round),
  updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, nomor_tanding_id, venue_id, match_date, status, round, created_at, updated_at, deleted_at, deleted_by, delete_reason
`

type UpdateMatchParams struct {
	ID      pgtype.UUID        `json:"id"`
	Column2 pgtype.UUID        `json:"column_2"`
	Column3 pgtype.UUID        `json:"column_3"`
	Column4 pgtype.Timestamptz `json:"column_4"`
	Column5 string             `json:"column_5"`
	Column6 string             `json:"column_6"`
}

func (q *Queries) UpdateMatch(ctx context.Context, arg UpdateMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, updateMatch,
		arg.ID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.NomorTandingID,
		&i.VenueID,
		&i.MatchDate,
		&i.Status,
		&i.Round,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.DeleteReason,
	)
	return i, err
}

const updateVenue = `-- name: UpdateVenue :one
UPDATE venues
SET 
  name = COALESCE(NULLIF($2::text, ''), name),
  address = COALESCE(NULLIF($3::text, ''), address),
  capacity = COALESCE(NULLIF($4::int, 0), capacity),
  city = COALESCE(NULLIF($5::text, ''), city),
  updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, address, capacity, created_at, updated_at, city, deleted_at, deleted_by, delete_reason
`

type UpdateVenueParams struct {
	ID      pgtype.UUID `json:"id"`
	Column2 string      `json:"column_2"`
	Column3 string      `json:"column_3"`
	Column4 int32       `json:"column_4"`
	Column5 string      `json:"column_5"`
}

func (q *Queries) UpdateVenue(ctx context.Context, arg UpdateVenueParams) (Venue, error) {
	row := q.db.QueryRow(ctx, updateVenue,
		arg.ID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.City,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.DeleteReason,
	)
	return i, err
}
