ALTER TABLE venues 
  ADD COLUMN IF NOT EXISTS image_url TEXT,
  ADD COLUMN IF NOT EXISTS latitude DECIMAL(10, 8),
  ADD COLUMN IF NOT EXISTS longitude DECIMAL(11, 8),
  ADD COLUMN IF NOT EXISTS map_route_url TEXT,
  ADD COLUMN IF NOT EXISTS city_guide_ids UUID[],
  ADD COLUMN IF NOT EXISTS cabor_ids UUID[],
  ADD COLUMN IF NOT EXISTS facilities TEXT,
  ADD COLUMN IF NOT EXISTS readiness_status VARCHAR(50) DEFAULT 'Persiapan',
  ADD COLUMN IF NOT EXISTS contact_person VARCHAR(255);
