// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cabor struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	Description       pgtype.Text        `json:"description"`
	IconUrl           pgtype.Text        `json:"icon_url"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Kategori          pgtype.Text        `json:"kategori"`
	TotalMedali       pgtype.Int4        `json:"total_medali"`
	TechnicalDelegate pgtype.Text        `json:"technical_delegate"`
	Status            pgtype.Text        `json:"status"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy         pgtype.Text        `json:"deleted_by"`
	DeleteReason      pgtype.Text        `json:"delete_reason"`
}

type CityGuide struct {
	ID           pgtype.UUID        `json:"id"`
	Title        string             `json:"title"`
	Category     string             `json:"category"`
	Description  pgtype.Text        `json:"description"`
	Address      pgtype.Text        `json:"address"`
	ImageUrl     pgtype.Text        `json:"image_url"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy    pgtype.Text        `json:"deleted_by"`
	DeleteReason pgtype.Text        `json:"delete_reason"`
	Latitude     pgtype.Float8      `json:"latitude"`
	Longitude    pgtype.Float8      `json:"longitude"`
}

type Kontingen struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	RegionType   string             `json:"region_type"`
	LogoUrl      pgtype.Text        `json:"logo_url"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy    pgtype.Text        `json:"deleted_by"`
	DeleteReason pgtype.Text        `json:"delete_reason"`
}

type MediaAsset struct {
	ID           pgtype.UUID        `json:"id"`
	FileName     string             `json:"file_name"`
	FileUrl      string             `json:"file_url"`
	MimeType     pgtype.Text        `json:"mime_type"`
	FileSize     pgtype.Int4        `json:"file_size"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy    pgtype.Text        `json:"deleted_by"`
	DeleteReason pgtype.Text        `json:"delete_reason"`
}

type NomorTanding struct {
	ID             pgtype.UUID        `json:"id"`
	CaborID        pgtype.UUID        `json:"cabor_id"`
	Name           string             `json:"name"`
	GenderCategory string             `json:"gender_category"`
	MatchType      string             `json:"match_type"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy      pgtype.Text        `json:"deleted_by"`
	DeleteReason   pgtype.Text        `json:"delete_reason"`
}
