// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cabor struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	Description       pgtype.Text        `json:"description"`
	IconUrl           pgtype.Text        `json:"icon_url"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Kategori          pgtype.Text        `json:"kategori"`
	TotalMedali       pgtype.Int4        `json:"total_medali"`
	TechnicalDelegate pgtype.Text        `json:"technical_delegate"`
	Status            pgtype.Text        `json:"status"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy         pgtype.Text        `json:"deleted_by"`
	DeleteReason      pgtype.Text        `json:"delete_reason"`
	Slug              string             `json:"slug"`
	HeroImageUrl      pgtype.Text        `json:"hero_image_url"`
}

type CityGuide struct {
	ID           pgtype.UUID        `json:"id"`
	Title        string             `json:"title"`
	Category     string             `json:"category"`
	Description  pgtype.Text        `json:"description"`
	Address      pgtype.Text        `json:"address"`
	ImageUrl     pgtype.Text        `json:"image_url"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy    pgtype.Text        `json:"deleted_by"`
	DeleteReason pgtype.Text        `json:"delete_reason"`
	Latitude     pgtype.Float8      `json:"latitude"`
	Longitude    pgtype.Float8      `json:"longitude"`
	// Optional HTTPS Google Maps route URL. Consumers fall back to latitude/longitude when empty.
	MapRouteUrl  pgtype.Text `json:"map_route_url"`
	ContactPhone pgtype.Text `json:"contact_phone"`
	Whatsapp     pgtype.Text `json:"whatsapp"`
	Email        pgtype.Text `json:"email"`
	WebsiteUrl   pgtype.Text `json:"website_url"`
	InstagramUrl pgtype.Text `json:"instagram_url"`
	FacebookUrl  pgtype.Text `json:"facebook_url"`
	TiktokUrl    pgtype.Text `json:"tiktok_url"`
	// Jenis layanan, misalnya nasi kotak, prasmanan, antar-jemput, atau sewa kendaraan.
	ServiceTypes   []string    `json:"service_types"`
	ServiceArea    pgtype.Text `json:"service_area"`
	OperatingHours pgtype.Text `json:"operating_hours"`
	PriceRange     pgtype.Text `json:"price_range"`
	// Jenis armada untuk kategori Info Travel/Jasa Transportasi.
	FleetTypes []string `json:"fleet_types"`
	// Jumlah seluruh unit armada aktif yang ditawarkan penyedia transportasi.
	FleetCount pgtype.Int4 `json:"fleet_count"`
}

type Hero struct {
	ID                 pgtype.UUID        `json:"id"`
	Title              string             `json:"title"`
	HighlightText      pgtype.Text        `json:"highlight_text"`
	Description        string             `json:"description"`
	BackgroundImageUrl string             `json:"background_image_url"`
	IsActive           bool               `json:"is_active"`
	CreatedBy          pgtype.Text        `json:"created_by"`
	UpdatedBy          pgtype.Text        `json:"updated_by"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy          pgtype.Text        `json:"deleted_by"`
	DeleteReason       pgtype.Text        `json:"delete_reason"`
}

type Kontingen struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	RegionType   string             `json:"region_type"`
	LogoUrl      pgtype.Text        `json:"logo_url"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy    pgtype.Text        `json:"deleted_by"`
	DeleteReason pgtype.Text        `json:"delete_reason"`
}

type MediaAsset struct {
	ID           pgtype.UUID        `json:"id"`
	FileName     string             `json:"file_name"`
	FileUrl      string             `json:"file_url"`
	MimeType     pgtype.Text        `json:"mime_type"`
	FileSize     pgtype.Int4        `json:"file_size"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy    pgtype.Text        `json:"deleted_by"`
	DeleteReason pgtype.Text        `json:"delete_reason"`
}

type NomorTanding struct {
	ID             pgtype.UUID        `json:"id"`
	CaborID        pgtype.UUID        `json:"cabor_id"`
	Name           string             `json:"name"`
	GenderCategory string             `json:"gender_category"`
	MatchType      string             `json:"match_type"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy      pgtype.Text        `json:"deleted_by"`
	DeleteReason   pgtype.Text        `json:"delete_reason"`
}
