// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCityGuides = `-- name: CountCityGuides :one
SELECT COUNT(*) FROM city_guides
WHERE deleted_at IS NULL
  AND category = COALESCE(NULLIF($1::text, ''), category)
  AND (
    NULLIF($2::text, '') IS NULL
    OR title ILIKE '%' || $2::text || '%' ESCAPE '\'
    OR COALESCE(description, '') ILIKE '%' || $2::text || '%' ESCAPE '\'
    OR COALESCE(address, '') ILIKE '%' || $2::text || '%' ESCAPE '\'
    OR category ILIKE '%' || $2::text || '%' ESCAPE '\'
    OR COALESCE(contact_phone, '') ILIKE '%' || $2::text || '%' ESCAPE '\'
    OR COALESCE(whatsapp, '') ILIKE '%' || $2::text || '%' ESCAPE '\'
    OR COALESCE(email, '') ILIKE '%' || $2::text || '%' ESCAPE '\'
  )
`

type CountCityGuidesParams struct {
	Category string `json:"category"`
	Search   string `json:"search"`
}

func (q *Queries) CountCityGuides(ctx context.Context, arg CountCityGuidesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCityGuides, arg.Category, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCabor = `-- name: CreateCabor :one
INSERT INTO cabors (name, description, icon_url, hero_image_url, kategori, total_medali, technical_delegate, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, description, icon_url, created_at, updated_at, kategori, total_medali, technical_delegate, status, deleted_at, deleted_by, delete_reason, slug, hero_image_url
`

type CreateCaborParams struct {
	Name              string      `json:"name"`
	Description       pgtype.Text `json:"description"`
	IconUrl           pgtype.Text `json:"icon_url"`
	HeroImageUrl      pgtype.Text `json:"hero_image_url"`
	Kategori          pgtype.Text `json:"kategori"`
	TotalMedali       pgtype.Int4 `json:"total_medali"`
	TechnicalDelegate pgtype.Text `json:"technical_delegate"`
	Status            pgtype.Text `json:"status"`
}

func (q *Queries) CreateCabor(ctx context.Context, arg CreateCaborParams) (Cabor, error) {
	row := q.db.QueryRow(ctx, createCabor,
		arg.Name,
		arg.Description,
		arg.IconUrl,
		arg.HeroImageUrl,
		arg.Kategori,
		arg.TotalMedali,
		arg.TechnicalDelegate,
		arg.Status,
	)
	var i Cabor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IconUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kategori,
		&i.TotalMedali,
		&i.TechnicalDelegate,
		&i.Status,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.DeleteReason,
		&i.Slug,
		&i.HeroImageUrl,
	)
	return i, err
}

const createCityGuide = `-- name: CreateCityGuide :one
INSERT INTO city_guides (
  title, category, description, address, image_url, latitude, longitude, map_route_url,
  contact_phone, whatsapp, email, website_url, instagram_url, facebook_url, tiktok_url,
  service_types, service_area, operating_hours, price_range, fleet_types, fleet_count
)
VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8,
  $9, $10, $11, $12, $13, $14, $15,
  $16, $17, $18, $19, $20, $21
)
RETURNING id, title, category, description, address, image_url, created_at, updated_at, deleted_at, deleted_by, delete_reason, latitude, longitude, map_route_url, contact_phone, whatsapp, email, website_url, instagram_url, facebook_url, tiktok_url, service_types, service_area, operating_hours, price_range, fleet_types, fleet_count
`

type CreateCityGuideParams struct {
	Title          string        `json:"title"`
	Category       string        `json:"category"`
	Description    pgtype.Text   `json:"description"`
	Address        pgtype.Text   `json:"address"`
	ImageUrl       pgtype.Text   `json:"image_url"`
	Latitude       pgtype.Float8 `json:"latitude"`
	Longitude      pgtype.Float8 `json:"longitude"`
	MapRouteUrl    pgtype.Text   `json:"map_route_url"`
	ContactPhone   pgtype.Text   `json:"contact_phone"`
	Whatsapp       pgtype.Text   `json:"whatsapp"`
	Email          pgtype.Text   `json:"email"`
	WebsiteUrl     pgtype.Text   `json:"website_url"`
	InstagramUrl   pgtype.Text   `json:"instagram_url"`
	FacebookUrl    pgtype.Text   `json:"facebook_url"`
	TiktokUrl      pgtype.Text   `json:"tiktok_url"`
	ServiceTypes   []string      `json:"service_types"`
	ServiceArea    pgtype.Text   `json:"service_area"`
	OperatingHours pgtype.Text   `json:"operating_hours"`
	PriceRange     pgtype.Text   `json:"price_range"`
	FleetTypes     []string      `json:"fleet_types"`
	FleetCount     pgtype.Int4   `json:"fleet_count"`
}

func (q *Queries) CreateCityGuide(ctx context.Context, arg CreateCityGuideParams) (CityGuide, error) {
	row := q.db.QueryRow(ctx, createCityGuide,
		arg.Title,
		arg.Category,
		arg.Description,
		arg.Address,
		arg.ImageUrl,
		arg.Latitude,
		arg.Longitude,
		arg.MapRouteUrl,
		arg.ContactPhone,
		arg.Whatsapp,
		arg.Email,
		arg.WebsiteUrl,
		arg.InstagramUrl,
		arg.FacebookUrl,
		arg.TiktokUrl,
		arg.ServiceTypes,
		arg.ServiceArea,
		arg.OperatingHours,
		arg.PriceRange,
		arg.FleetTypes,
		arg.FleetCount,
	)
	var i CityGuide
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Category,
		&i.Description,
		&i.Address,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.DeleteReason,
		&i.Latitude,
		&i.Longitude,
		&i.MapRouteUrl,
		&i.ContactPhone,
		&i.Whatsapp,
		&i.Email,
		&i.WebsiteUrl,
		&i.InstagramUrl,
		&i.FacebookUrl,
		&i.TiktokUrl,
		&i.ServiceTypes,
		&i.ServiceArea,
		&i.OperatingHours,
		&i.PriceRange,
		&i.FleetTypes,
		&i.FleetCount,
	)
	return i, err
}

const createHero = `-- name: CreateHero :one
WITH deactivated AS (
  UPDATE heroes AS current_hero
  SET is_active = FALSE, updated_at = NOW(), updated_by = $6
  WHERE $5::boolean = TRUE AND current_hero.is_active = TRUE AND current_hero.deleted_at IS NULL
  RETURNING current_hero.id
)
INSERT INTO heroes (title, highlight_text, description, background_image_url, is_active, created_by, updated_by)
SELECT $1, NULLIF($2::text, ''), $3,
       $4, $5, $6, $6
FROM (SELECT COUNT(*) FROM deactivated) synchronization
RETURNING id, title, highlight_text, description, background_image_url, is_active, created_by, updated_by, created_at, updated_at, deleted_at, deleted_by, delete_reason
`

type CreateHeroParams struct {
	Title              string      `json:"title"`
	HighlightText      string      `json:"highlight_text"`
	Description        string      `json:"description"`
	BackgroundImageUrl string      `json:"background_image_url"`
	IsActive           bool        `json:"is_active"`
	Actor              pgtype.Text `json:"actor"`
}

func (q *Queries) CreateHero(ctx context.Context, arg CreateHeroParams) (Hero, error) {
	row := q.db.QueryRow(ctx, createHero,
		arg.Title,
		arg.HighlightText,
		arg.Description,
		arg.BackgroundImageUrl,
		arg.IsActive,
		arg.Actor,
	)
	var i Hero
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.HighlightText,
		&i.Description,
		&i.BackgroundImageUrl,
		&i.IsActive,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.DeleteReason,
	)
	return i, err
}

const createKontingen = `-- name: CreateKontingen :one
INSERT INTO kontingens (name, region_type, logo_url)
VALUES ($1, $2, $3)
RETURNING id, name, region_type, logo_url, created_at, updated_at, deleted_at, deleted_by, delete_reason
`

type CreateKontingenParams struct {
	Name       string      `json:"name"`
	RegionType string      `json:"region_type"`
	LogoUrl    pgtype.Text `json:"logo_url"`
}

func (q *Queries) CreateKontingen(ctx context.Context, arg CreateKontingenParams) (Kontingen, error) {
	row := q.db.QueryRow(ctx, createKontingen, arg.Name, arg.RegionType, arg.LogoUrl)
	var i Kontingen
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RegionType,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.DeleteReason,
	)
	return i, err
}

const createMedia = `-- name: CreateMedia :one
INSERT INTO media_assets (
  file_name, file_url, mime_type, file_size
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, file_name, file_url, mime_type, file_size, created_at, updated_at, deleted_at, deleted_by, delete_reason
`

type CreateMediaParams struct {
	FileName string      `json:"file_name"`
	FileUrl  string      `json:"file_url"`
	MimeType pgtype.Text `json:"mime_type"`
	FileSize pgtype.Int4 `json:"file_size"`
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, createMedia,
		arg.FileName,
		arg.FileUrl,
		arg.MimeType,
		arg.FileSize,
	)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.FileUrl,
		&i.MimeType,
		&i.FileSize,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.DeleteReason,
	)
	return i, err
}

const createNomorTanding = `-- name: CreateNomorTanding :one
INSERT INTO nomor_tandings (cabor_id, name, gender_category, match_type)
VALUES ($1, $2, $3, $4)
RETURNING id, cabor_id, name, gender_category, match_type, created_at, updated_at, deleted_at, deleted_by, delete_reason
`

type CreateNomorTandingParams struct {
	CaborID        pgtype.UUID `json:"cabor_id"`
	Name           string      `json:"name"`
	GenderCategory string      `json:"gender_category"`
	MatchType      string      `json:"match_type"`
}

func (q *Queries) CreateNomorTanding(ctx context.Context, arg CreateNomorTandingParams) (NomorTanding, error) {
	row := q.db.QueryRow(ctx, createNomorTanding,
		arg.CaborID,
		arg.Name,
		arg.GenderCategory,
		arg.MatchType,
	)
	var i NomorTanding
	err := row.Scan(
		&i.ID,
		&i.CaborID,
		&i.Name,
		&i.GenderCategory,
		&i.MatchType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.DeleteReason,
	)
	return i, err
}

const getActiveHero = `-- name: GetActiveHero :one
SELECT id, title, highlight_text, description, background_image_url, is_active, created_by, updated_by, created_at, updated_at, deleted_at, deleted_by, delete_reason FROM heroes
WHERE is_active = TRUE AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetActiveHero(ctx context.Context) (Hero, error) {
	row := q.db.QueryRow(ctx, getActiveHero)
	var i Hero
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.HighlightText,
		&i.Description,
		&i.BackgroundImageUrl,
		&i.IsActive,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.DeleteReason,
	)
	return i, err
}

const getCaborByID = `-- name: GetCaborByID :one
SELECT id, name, description, icon_url, created_at, updated_at, kategori, total_medali, technical_delegate, status, deleted_at, deleted_by, delete_reason, slug, hero_image_url FROM cabors WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetCaborByID(ctx context.Context, id pgtype.UUID) (Cabor, error) {
	row := q.db.QueryRow(ctx, getCaborByID, id)
	var i Cabor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IconUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kategori,
		&i.TotalMedali,
		&i.TechnicalDelegate,
		&i.Status,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.DeleteReason,
		&i.Slug,
		&i.HeroImageUrl,
	)
	return i, err
}

const getCaborByIdentifier = `-- name: GetCaborByIdentifier :one
SELECT id, name, description, icon_url, created_at, updated_at, kategori, total_medali, technical_delegate, status, deleted_at, deleted_by, delete_reason, slug, hero_image_url FROM cabors
WHERE deleted_at IS NULL
  AND (id::text = $1::text OR slug = $1::text)
LIMIT 1
`

func (q *Queries) GetCaborByIdentifier(ctx context.Context, identifier string) (Cabor, error) {
	row := q.db.QueryRow(ctx, getCaborByIdentifier, identifier)
	var i Cabor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IconUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kategori,
		&i.TotalMedali,
		&i.TechnicalDelegate,
		&i.Status,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.DeleteReason,
		&i.Slug,
		&i.HeroImageUrl,
	)
	return i, err
}

const getCityGuideByID = `-- name: GetCityGuideByID :one
SELECT id, title, category, description, address, image_url, created_at, updated_at, deleted_at, deleted_by, delete_reason, latitude, longitude, map_route_url, contact_phone, whatsapp, email, website_url, instagram_url, facebook_url, tiktok_url, service_types, service_area, operating_hours, price_range, fleet_types, fleet_count FROM city_guides WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetCityGuideByID(ctx context.Context, id pgtype.UUID) (CityGuide, error) {
	row := q.db.QueryRow(ctx, getCityGuideByID, id)
	var i CityGuide
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Category,
		&i.Description,
		&i.Address,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.DeleteReason,
		&i.Latitude,
		&i.Longitude,
		&i.MapRouteUrl,
		&i.ContactPhone,
		&i.Whatsapp,
		&i.Email,
		&i.WebsiteUrl,
		&i.InstagramUrl,
		&i.FacebookUrl,
		&i.TiktokUrl,
		&i.ServiceTypes,
		&i.ServiceArea,
		&i.OperatingHours,
		&i.PriceRange,
		&i.FleetTypes,
		&i.FleetCount,
	)
	return i, err
}

const getHeroByID = `-- name: GetHeroByID :one
SELECT id, title, highlight_text, description, background_image_url, is_active, created_by, updated_by, created_at, updated_at, deleted_at, deleted_by, delete_reason FROM heroes
WHERE id = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetHeroByID(ctx context.Context, id pgtype.UUID) (Hero, error) {
	row := q.db.QueryRow(ctx, getHeroByID, id)
	var i Hero
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.HighlightText,
		&i.Description,
		&i.BackgroundImageUrl,
		&i.IsActive,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.DeleteReason,
	)
	return i, err
}

const getKontingenByID = `-- name: GetKontingenByID :one
SELECT id, name, region_type, logo_url, created_at, updated_at, deleted_at, deleted_by, delete_reason FROM kontingens WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetKontingenByID(ctx context.Context, id pgtype.UUID) (Kontingen, error) {
	row := q.db.QueryRow(ctx, getKontingenByID, id)
	var i Kontingen
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RegionType,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.DeleteReason,
	)
	return i, err
}

const getMedia = `-- name: GetMedia :many
SELECT id, file_name, file_url, mime_type, file_size, created_at, updated_at, deleted_at, deleted_by, delete_reason FROM media_assets
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetMedia(ctx context.Context) ([]MediaAsset, error) {
	rows, err := q.db.Query(ctx, getMedia)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaAsset
	for rows.Next() {
		var i MediaAsset
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.FileUrl,
			&i.MimeType,
			&i.FileSize,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.DeleteReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMediaByID = `-- name: GetMediaByID :one
SELECT id, file_name, file_url, mime_type, file_size, created_at, updated_at, deleted_at, deleted_by, delete_reason FROM media_assets
WHERE id = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetMediaByID(ctx context.Context, id pgtype.UUID) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, getMediaByID, id)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.FileUrl,
		&i.MimeType,
		&i.FileSize,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.DeleteReason,
	)
	return i, err
}

const getNomorTandingByID = `-- name: GetNomorTandingByID :one
SELECT id, cabor_id, name, gender_category, match_type, created_at, updated_at, deleted_at, deleted_by, delete_reason FROM nomor_tandings WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetNomorTandingByID(ctx context.Context, id pgtype.UUID) (NomorTanding, error) {
	row := q.db.QueryRow(ctx, getNomorTandingByID, id)
	var i NomorTanding
	err := row.Scan(
		&i.ID,
		&i.CaborID,
		&i.Name,
		&i.GenderCategory,
		&i.MatchType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.DeleteReason,
	)
	return i, err
}

const listCabors = `-- name: ListCabors :many
SELECT id, name, description, icon_url, created_at, updated_at, kategori, total_medali, technical_delegate, status, deleted_at, deleted_by, delete_reason, slug, hero_image_url FROM cabors
WHERE deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) ListCabors(ctx context.Context) ([]Cabor, error) {
	rows, err := q.db.Query(ctx, listCabors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cabor
	for rows.Next() {
		var i Cabor
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IconUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Kategori,
			&i.TotalMedali,
			&i.TechnicalDelegate,
			&i.Status,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.DeleteReason,
			&i.Slug,
			&i.HeroImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCityGuides = `-- name: ListCityGuides :many
SELECT id, title, category, description, address, image_url, created_at, updated_at, deleted_at, deleted_by, delete_reason, latitude, longitude, map_route_url, contact_phone, whatsapp, email, website_url, instagram_url, facebook_url, tiktok_url, service_types, service_area, operating_hours, price_range, fleet_types, fleet_count FROM city_guides
WHERE deleted_at IS NULL
  AND category = COALESCE(NULLIF($1::text, ''), category)
  AND (
    NULLIF($2::text, '') IS NULL
    OR title ILIKE '%' || $2::text || '%' ESCAPE '\'
    OR COALESCE(description, '') ILIKE '%' || $2::text || '%' ESCAPE '\'
    OR COALESCE(address, '') ILIKE '%' || $2::text || '%' ESCAPE '\'
    OR category ILIKE '%' || $2::text || '%' ESCAPE '\'
  )
ORDER BY title ASC
`

type ListCityGuidesParams struct {
	Category string `json:"category"`
	Search   string `json:"search"`
}

func (q *Queries) ListCityGuides(ctx context.Context, arg ListCityGuidesParams) ([]CityGuide, error) {
	rows, err := q.db.Query(ctx, listCityGuides, arg.Category, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CityGuide
	for rows.Next() {
		var i CityGuide
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Category,
			&i.Description,
			&i.Address,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.DeleteReason,
			&i.Latitude,
			&i.Longitude,
			&i.MapRouteUrl,
			&i.ContactPhone,
			&i.Whatsapp,
			&i.Email,
			&i.WebsiteUrl,
			&i.InstagramUrl,
			&i.FacebookUrl,
			&i.TiktokUrl,
			&i.ServiceTypes,
			&i.ServiceArea,
			&i.OperatingHours,
			&i.PriceRange,
			&i.FleetTypes,
			&i.FleetCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCityGuidesPaginated = `-- name: ListCityGuidesPaginated :many
SELECT id, title, category, description, address, image_url, created_at, updated_at, deleted_at, deleted_by, delete_reason, latitude, longitude, map_route_url, contact_phone, whatsapp, email, website_url, instagram_url, facebook_url, tiktok_url, service_types, service_area, operating_hours, price_range, fleet_types, fleet_count FROM city_guides
WHERE deleted_at IS NULL
  AND category = COALESCE(NULLIF($1::text, ''), category)
  AND (
    NULLIF($2::text, '') IS NULL
    OR title ILIKE '%' || $2::text || '%' ESCAPE '\'
    OR COALESCE(description, '') ILIKE '%' || $2::text || '%' ESCAPE '\'
    OR COALESCE(address, '') ILIKE '%' || $2::text || '%' ESCAPE '\'
    OR category ILIKE '%' || $2::text || '%' ESCAPE '\'
    OR COALESCE(contact_phone, '') ILIKE '%' || $2::text || '%' ESCAPE '\'
    OR COALESCE(whatsapp, '') ILIKE '%' || $2::text || '%' ESCAPE '\'
    OR COALESCE(email, '') ILIKE '%' || $2::text || '%' ESCAPE '\'
  )
ORDER BY title ASC, id ASC
LIMIT $4::integer
OFFSET $3::integer
`

type ListCityGuidesPaginatedParams struct {
	Category   string `json:"category"`
	Search     string `json:"search"`
	PageOffset int32  `json:"page_offset"`
	PageLimit  int32  `json:"page_limit"`
}

func (q *Queries) ListCityGuidesPaginated(ctx context.Context, arg ListCityGuidesPaginatedParams) ([]CityGuide, error) {
	rows, err := q.db.Query(ctx, listCityGuidesPaginated,
		arg.Category,
		arg.Search,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CityGuide
	for rows.Next() {
		var i CityGuide
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Category,
			&i.Description,
			&i.Address,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.DeleteReason,
			&i.Latitude,
			&i.Longitude,
			&i.MapRouteUrl,
			&i.ContactPhone,
			&i.Whatsapp,
			&i.Email,
			&i.WebsiteUrl,
			&i.InstagramUrl,
			&i.FacebookUrl,
			&i.TiktokUrl,
			&i.ServiceTypes,
			&i.ServiceArea,
			&i.OperatingHours,
			&i.PriceRange,
			&i.FleetTypes,
			&i.FleetCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHeroes = `-- name: ListHeroes :many
SELECT id, title, highlight_text, description, background_image_url, is_active, created_by, updated_by, created_at, updated_at, deleted_at, deleted_by, delete_reason FROM heroes
WHERE deleted_at IS NULL
ORDER BY is_active DESC, updated_at DESC
`

func (q *Queries) ListHeroes(ctx context.Context) ([]Hero, error) {
	rows, err := q.db.Query(ctx, listHeroes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Hero
	for rows.Next() {
		var i Hero
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.HighlightText,
			&i.Description,
			&i.BackgroundImageUrl,
			&i.IsActive,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.DeleteReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKontingens = `-- name: ListKontingens :many
SELECT id, name, region_type, logo_url, created_at, updated_at, deleted_at, deleted_by, delete_reason FROM kontingens
WHERE deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) ListKontingens(ctx context.Context) ([]Kontingen, error) {
	rows, err := q.db.Query(ctx, listKontingens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Kontingen
	for rows.Next() {
		var i Kontingen
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RegionType,
			&i.LogoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.DeleteReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNomorTandings = `-- name: ListNomorTandings :many
SELECT id, cabor_id, name, gender_category, match_type, created_at, updated_at, deleted_at, deleted_by, delete_reason FROM nomor_tandings
WHERE deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) ListNomorTandings(ctx context.Context) ([]NomorTanding, error) {
	rows, err := q.db.Query(ctx, listNomorTandings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NomorTanding
	for rows.Next() {
		var i NomorTanding
		if err := rows.Scan(
			&i.ID,
			&i.CaborID,
			&i.Name,
			&i.GenderCategory,
			&i.MatchType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.DeleteReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCabor = `-- name: UpdateCabor :one
UPDATE cabors
SET
  name = COALESCE(NULLIF($2::text, ''), name),
  description = COALESCE(NULLIF($3::text, ''), description),
  icon_url = COALESCE(NULLIF($4::text, ''), icon_url),
  hero_image_url = NULLIF($5::text, ''),
  kategori = COALESCE(NULLIF($6::text, ''), kategori),
  total_medali = COALESCE(NULLIF($7::integer, 0), total_medali),
  technical_delegate = COALESCE(NULLIF($8::text, ''), technical_delegate),
  status = COALESCE(NULLIF($9::text, ''), status),
  updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, description, icon_url, created_at, updated_at, kategori, total_medali, technical_delegate, status, deleted_at, deleted_by, delete_reason, slug, hero_image_url
`

type UpdateCaborParams struct {
	ID      pgtype.UUID `json:"id"`
	Column2 string      `json:"column_2"`
	Column3 string      `json:"column_3"`
	Column4 string      `json:"column_4"`
	Column5 string      `json:"column_5"`
	Column6 string      `json:"column_6"`
	Column7 int32       `json:"column_7"`
	Column8 string      `json:"column_8"`
	Column9 string      `json:"column_9"`
}

func (q *Queries) UpdateCabor(ctx context.Context, arg UpdateCaborParams) (Cabor, error) {
	row := q.db.QueryRow(ctx, updateCabor,
		arg.ID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Column9,
	)
	var i Cabor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IconUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kategori,
		&i.TotalMedali,
		&i.TechnicalDelegate,
		&i.Status,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.DeleteReason,
		&i.Slug,
		&i.HeroImageUrl,
	)
	return i, err
}

const updateCityGuide = `-- name: UpdateCityGuide :one
UPDATE city_guides
SET
  title = $2,
  category = $3,
  description = NULLIF($4::text, ''),
  address = NULLIF($5::text, ''),
  image_url = NULLIF($6::text, ''),
  latitude = $7,
  longitude = $8,
  map_route_url = NULLIF($9::text, ''),
  contact_phone = NULLIF($10::text, ''),
  whatsapp = NULLIF($11::text, ''),
  email = NULLIF($12::text, ''),
  website_url = NULLIF($13::text, ''),
  instagram_url = NULLIF($14::text, ''),
  facebook_url = NULLIF($15::text, ''),
  tiktok_url = NULLIF($16::text, ''),
  service_types = $17,
  service_area = NULLIF($18::text, ''),
  operating_hours = NULLIF($19::text, ''),
  price_range = NULLIF($20::text, ''),
  fleet_types = $21,
  fleet_count = $22,
  updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, title, category, description, address, image_url, created_at, updated_at, deleted_at, deleted_by, delete_reason, latitude, longitude, map_route_url, contact_phone, whatsapp, email, website_url, instagram_url, facebook_url, tiktok_url, service_types, service_area, operating_hours, price_range, fleet_types, fleet_count
`

type UpdateCityGuideParams struct {
	ID           pgtype.UUID   `json:"id"`
	Title        string        `json:"title"`
	Category     string        `json:"category"`
	Column4      string        `json:"column_4"`
	Column5      string        `json:"column_5"`
	Column6      string        `json:"column_6"`
	Latitude     pgtype.Float8 `json:"latitude"`
	Longitude    pgtype.Float8 `json:"longitude"`
	Column9      string        `json:"column_9"`
	Column10     string        `json:"column_10"`
	Column11     string        `json:"column_11"`
	Column12     string        `json:"column_12"`
	Column13     string        `json:"column_13"`
	Column14     string        `json:"column_14"`
	Column15     string        `json:"column_15"`
	Column16     string        `json:"column_16"`
	ServiceTypes []string      `json:"service_types"`
	Column18     string        `json:"column_18"`
	Column19     string        `json:"column_19"`
	Column20     string        `json:"column_20"`
	FleetTypes   []string      `json:"fleet_types"`
	FleetCount   pgtype.Int4   `json:"fleet_count"`
}

func (q *Queries) UpdateCityGuide(ctx context.Context, arg UpdateCityGuideParams) (CityGuide, error) {
	row := q.db.QueryRow(ctx, updateCityGuide,
		arg.ID,
		arg.Title,
		arg.Category,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Latitude,
		arg.Longitude,
		arg.Column9,
		arg.Column10,
		arg.Column11,
		arg.Column12,
		arg.Column13,
		arg.Column14,
		arg.Column15,
		arg.Column16,
		arg.ServiceTypes,
		arg.Column18,
		arg.Column19,
		arg.Column20,
		arg.FleetTypes,
		arg.FleetCount,
	)
	var i CityGuide
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Category,
		&i.Description,
		&i.Address,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.DeleteReason,
		&i.Latitude,
		&i.Longitude,
		&i.MapRouteUrl,
		&i.ContactPhone,
		&i.Whatsapp,
		&i.Email,
		&i.WebsiteUrl,
		&i.InstagramUrl,
		&i.FacebookUrl,
		&i.TiktokUrl,
		&i.ServiceTypes,
		&i.ServiceArea,
		&i.OperatingHours,
		&i.PriceRange,
		&i.FleetTypes,
		&i.FleetCount,
	)
	return i, err
}

const updateHero = `-- name: UpdateHero :one
WITH deactivated AS (
  UPDATE heroes AS current_hero
  SET is_active = FALSE, updated_at = NOW(), updated_by = $6
  WHERE $5::boolean = TRUE
    AND current_hero.id <> $7
    AND current_hero.is_active = TRUE
    AND current_hero.deleted_at IS NULL
    AND EXISTS (
      SELECT 1 FROM heroes AS update_target
      WHERE update_target.id = $7 AND update_target.deleted_at IS NULL
    )
  RETURNING current_hero.id
)
UPDATE heroes AS target
SET title = $1,
    highlight_text = NULLIF($2::text, ''),
    description = $3,
    background_image_url = $4,
    is_active = $5,
    updated_by = $6,
    updated_at = NOW()
WHERE target.id = $7
  AND target.deleted_at IS NULL
  AND (SELECT COUNT(*) FROM deactivated) >= 0
RETURNING id, title, highlight_text, description, background_image_url, is_active, created_by, updated_by, created_at, updated_at, deleted_at, deleted_by, delete_reason
`

type UpdateHeroParams struct {
	Title              string      `json:"title"`
	HighlightText      string      `json:"highlight_text"`
	Description        string      `json:"description"`
	BackgroundImageUrl string      `json:"background_image_url"`
	IsActive           bool        `json:"is_active"`
	Actor              pgtype.Text `json:"actor"`
	ID                 pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateHero(ctx context.Context, arg UpdateHeroParams) (Hero, error) {
	row := q.db.QueryRow(ctx, updateHero,
		arg.Title,
		arg.HighlightText,
		arg.Description,
		arg.BackgroundImageUrl,
		arg.IsActive,
		arg.Actor,
		arg.ID,
	)
	var i Hero
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.HighlightText,
		&i.Description,
		&i.BackgroundImageUrl,
		&i.IsActive,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.DeleteReason,
	)
	return i, err
}

const updateKontingen = `-- name: UpdateKontingen :one
UPDATE kontingens
SET
  name = COALESCE(NULLIF($2::text, ''), name),
  region_type = COALESCE(NULLIF($3::text, ''), region_type),
  logo_url = COALESCE(NULLIF($4::text, ''), logo_url),
  updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, region_type, logo_url, created_at, updated_at, deleted_at, deleted_by, delete_reason
`

type UpdateKontingenParams struct {
	ID      pgtype.UUID `json:"id"`
	Column2 string      `json:"column_2"`
	Column3 string      `json:"column_3"`
	Column4 string      `json:"column_4"`
}

func (q *Queries) UpdateKontingen(ctx context.Context, arg UpdateKontingenParams) (Kontingen, error) {
	row := q.db.QueryRow(ctx, updateKontingen,
		arg.ID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var i Kontingen
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RegionType,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.DeleteReason,
	)
	return i, err
}

const updateNomorTanding = `-- name: UpdateNomorTanding :one
UPDATE nomor_tandings
SET
  cabor_id = $2,
  name = $3,
  gender_category = $4,
  match_type = $5,
  updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, cabor_id, name, gender_category, match_type, created_at, updated_at, deleted_at, deleted_by, delete_reason
`

type UpdateNomorTandingParams struct {
	ID             pgtype.UUID `json:"id"`
	CaborID        pgtype.UUID `json:"cabor_id"`
	Name           string      `json:"name"`
	GenderCategory string      `json:"gender_category"`
	MatchType      string      `json:"match_type"`
}

func (q *Queries) UpdateNomorTanding(ctx context.Context, arg UpdateNomorTandingParams) (NomorTanding, error) {
	row := q.db.QueryRow(ctx, updateNomorTanding,
		arg.ID,
		arg.CaborID,
		arg.Name,
		arg.GenderCategory,
		arg.MatchType,
	)
	var i NomorTanding
	err := row.Scan(
		&i.ID,
		&i.CaborID,
		&i.Name,
		&i.GenderCategory,
		&i.MatchType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.DeleteReason,
	)
	return i, err
}
