// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountCityGuides(ctx context.Context, arg CountCityGuidesParams) (int64, error)
	CreateCabor(ctx context.Context, arg CreateCaborParams) (Cabor, error)
	CreateCityGuide(ctx context.Context, arg CreateCityGuideParams) (CityGuide, error)
	CreateHero(ctx context.Context, arg CreateHeroParams) (Hero, error)
	CreateKontingen(ctx context.Context, arg CreateKontingenParams) (Kontingen, error)
	CreateMedia(ctx context.Context, arg CreateMediaParams) (MediaAsset, error)
	CreateNomorTanding(ctx context.Context, arg CreateNomorTandingParams) (NomorTanding, error)
	GetActiveHero(ctx context.Context) (Hero, error)
	GetCaborByID(ctx context.Context, id pgtype.UUID) (Cabor, error)
	GetCaborByIdentifier(ctx context.Context, identifier string) (Cabor, error)
	GetCityGuideByID(ctx context.Context, id pgtype.UUID) (CityGuide, error)
	GetHeroByID(ctx context.Context, id pgtype.UUID) (Hero, error)
	GetKontingenByID(ctx context.Context, id pgtype.UUID) (Kontingen, error)
	GetMedia(ctx context.Context) ([]MediaAsset, error)
	GetMediaByID(ctx context.Context, id pgtype.UUID) (MediaAsset, error)
	GetNomorTandingByID(ctx context.Context, id pgtype.UUID) (NomorTanding, error)
	ListCabors(ctx context.Context) ([]Cabor, error)
	ListCityGuides(ctx context.Context, arg ListCityGuidesParams) ([]CityGuide, error)
	ListCityGuidesPaginated(ctx context.Context, arg ListCityGuidesPaginatedParams) ([]CityGuide, error)
	ListHeroes(ctx context.Context) ([]Hero, error)
	ListKontingens(ctx context.Context) ([]Kontingen, error)
	ListNomorTandings(ctx context.Context) ([]NomorTanding, error)
	UpdateCabor(ctx context.Context, arg UpdateCaborParams) (Cabor, error)
	UpdateCityGuide(ctx context.Context, arg UpdateCityGuideParams) (CityGuide, error)
	UpdateHero(ctx context.Context, arg UpdateHeroParams) (Hero, error)
	UpdateKontingen(ctx context.Context, arg UpdateKontingenParams) (Kontingen, error)
	UpdateNomorTanding(ctx context.Context, arg UpdateNomorTandingParams) (NomorTanding, error)
}

var _ Querier = (*Queries)(nil)
