// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCabor = `-- name: CreateCabor :one
INSERT INTO cabors (name, description, icon_url, kategori, total_medali, technical_delegate, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, description, icon_url, kategori, total_medali, technical_delegate, status, created_at, updated_at
`

type CreateCaborParams struct {
	Name              string      `json:"name"`
	Description       pgtype.Text `json:"description"`
	IconUrl           pgtype.Text `json:"icon_url"`
	Kategori          pgtype.Text `json:"kategori"`
	TotalMedali       pgtype.Int4 `json:"total_medali"`
	TechnicalDelegate pgtype.Text `json:"technical_delegate"`
	Status            pgtype.Text `json:"status"`
}

func (q *Queries) CreateCabor(ctx context.Context, arg CreateCaborParams) (Cabor, error) {
	row := q.db.QueryRow(ctx, createCabor,
		arg.Name,
		arg.Description,
		arg.IconUrl,
		arg.Kategori,
		arg.TotalMedali,
		arg.TechnicalDelegate,
		arg.Status,
	)
	var i Cabor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IconUrl,
		&i.Kategori,
		&i.TotalMedali,
		&i.TechnicalDelegate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createKontingen = `-- name: CreateKontingen :one
INSERT INTO kontingens (name, region_type, logo_url)
VALUES ($1, $2, $3)
RETURNING id, name, region_type, logo_url, created_at, updated_at
`

type CreateKontingenParams struct {
	Name       string      `json:"name"`
	RegionType string      `json:"region_type"`
	LogoUrl    pgtype.Text `json:"logo_url"`
}

func (q *Queries) CreateKontingen(ctx context.Context, arg CreateKontingenParams) (Kontingen, error) {
	row := q.db.QueryRow(ctx, createKontingen, arg.Name, arg.RegionType, arg.LogoUrl)
	var i Kontingen
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RegionType,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createNomorTanding = `-- name: CreateNomorTanding :one
INSERT INTO nomor_tandings (cabor_id, name, gender_category, match_type)
VALUES ($1, $2, $3, $4)
RETURNING id, cabor_id, name, gender_category, match_type, created_at, updated_at
`

type CreateNomorTandingParams struct {
	CaborID        pgtype.UUID `json:"cabor_id"`
	Name           string      `json:"name"`
	GenderCategory string      `json:"gender_category"`
	MatchType      string      `json:"match_type"`
}

func (q *Queries) CreateNomorTanding(ctx context.Context, arg CreateNomorTandingParams) (NomorTanding, error) {
	row := q.db.QueryRow(ctx, createNomorTanding,
		arg.CaborID,
		arg.Name,
		arg.GenderCategory,
		arg.MatchType,
	)
	var i NomorTanding
	err := row.Scan(
		&i.ID,
		&i.CaborID,
		&i.Name,
		&i.GenderCategory,
		&i.MatchType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCabor = `-- name: DeleteCabor :exec
DELETE FROM cabors WHERE id = $1
`

func (q *Queries) DeleteCabor(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCabor, id)
	return err
}

const deleteKontingen = `-- name: DeleteKontingen :exec
DELETE FROM kontingens WHERE id = $1
`

func (q *Queries) DeleteKontingen(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteKontingen, id)
	return err
}

const getCaborByID = `-- name: GetCaborByID :one
SELECT id, name, description, icon_url, kategori, total_medali, technical_delegate, status, created_at, updated_at FROM cabors WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCaborByID(ctx context.Context, id pgtype.UUID) (Cabor, error) {
	row := q.db.QueryRow(ctx, getCaborByID, id)
	var i Cabor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IconUrl,
		&i.Kategori,
		&i.TotalMedali,
		&i.TechnicalDelegate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getKontingenByID = `-- name: GetKontingenByID :one
SELECT id, name, region_type, logo_url, created_at, updated_at FROM kontingens WHERE id = $1 LIMIT 1
`

func (q *Queries) GetKontingenByID(ctx context.Context, id pgtype.UUID) (Kontingen, error) {
	row := q.db.QueryRow(ctx, getKontingenByID, id)
	var i Kontingen
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RegionType,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCabors = `-- name: ListCabors :many
SELECT id, name, description, icon_url, kategori, total_medali, technical_delegate, status, created_at, updated_at FROM cabors
ORDER BY name ASC
`

func (q *Queries) ListCabors(ctx context.Context) ([]Cabor, error) {
	rows, err := q.db.Query(ctx, listCabors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cabor
	for rows.Next() {
		var i Cabor
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IconUrl,
			&i.Kategori,
			&i.TotalMedali,
			&i.TechnicalDelegate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKontingens = `-- name: ListKontingens :many
SELECT id, name, region_type, logo_url, created_at, updated_at FROM kontingens
ORDER BY name ASC
`

func (q *Queries) ListKontingens(ctx context.Context) ([]Kontingen, error) {
	rows, err := q.db.Query(ctx, listKontingens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Kontingen
	for rows.Next() {
		var i Kontingen
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RegionType,
			&i.LogoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNomorTandings = `-- name: ListNomorTandings :many
SELECT id, cabor_id, name, gender_category, match_type, created_at, updated_at FROM nomor_tandings
ORDER BY name ASC
`

func (q *Queries) ListNomorTandings(ctx context.Context) ([]NomorTanding, error) {
	rows, err := q.db.Query(ctx, listNomorTandings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NomorTanding
	for rows.Next() {
		var i NomorTanding
		if err := rows.Scan(
			&i.ID,
			&i.CaborID,
			&i.Name,
			&i.GenderCategory,
			&i.MatchType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCabor = `-- name: UpdateCabor :one
UPDATE cabors
SET 
  name = COALESCE(NULLIF($2::text, ''), name),
  description = COALESCE(NULLIF($3::text, ''), description),
  icon_url = COALESCE(NULLIF($4::text, ''), icon_url),
  kategori = COALESCE(NULLIF($5::text, ''), kategori),
  total_medali = COALESCE(NULLIF($6::integer, 0), total_medali),
  technical_delegate = COALESCE(NULLIF($7::text, ''), technical_delegate),
  status = COALESCE(NULLIF($8::text, ''), status),
  updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, icon_url, kategori, total_medali, technical_delegate, status, created_at, updated_at
`

type UpdateCaborParams struct {
	ID      pgtype.UUID `json:"id"`
	Column2 string      `json:"column_2"`
	Column3 string      `json:"column_3"`
	Column4 string      `json:"column_4"`
	Column5 string      `json:"column_5"`
	Column6 int32       `json:"column_6"`
	Column7 string      `json:"column_7"`
	Column8 string      `json:"column_8"`
}

func (q *Queries) UpdateCabor(ctx context.Context, arg UpdateCaborParams) (Cabor, error) {
	row := q.db.QueryRow(ctx, updateCabor,
		arg.ID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
	)
	var i Cabor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IconUrl,
		&i.Kategori,
		&i.TotalMedali,
		&i.TechnicalDelegate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateKontingen = `-- name: UpdateKontingen :one
UPDATE kontingens
SET 
  name = COALESCE(NULLIF($2::text, ''), name),
  region_type = COALESCE(NULLIF($3::text, ''), region_type),
  logo_url = COALESCE(NULLIF($4::text, ''), logo_url),
  updated_at = NOW()
WHERE id = $1
RETURNING id, name, region_type, logo_url, created_at, updated_at
`

type UpdateKontingenParams struct {
	ID      pgtype.UUID `json:"id"`
	Column2 string      `json:"column_2"`
	Column3 string      `json:"column_3"`
	Column4 string      `json:"column_4"`
}

func (q *Queries) UpdateKontingen(ctx context.Context, arg UpdateKontingenParams) (Kontingen, error) {
	row := q.db.QueryRow(ctx, updateKontingen,
		arg.ID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var i Kontingen
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RegionType,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
