// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCabor(ctx context.Context, arg CreateCaborParams) (Cabor, error)
	CreateKontingen(ctx context.Context, arg CreateKontingenParams) (Kontingen, error)
	CreateNomorTanding(ctx context.Context, arg CreateNomorTandingParams) (NomorTanding, error)
	DeleteCabor(ctx context.Context, id pgtype.UUID) error
	DeleteKontingen(ctx context.Context, id pgtype.UUID) error
	GetCaborByID(ctx context.Context, id pgtype.UUID) (Cabor, error)
	GetKontingenByID(ctx context.Context, id pgtype.UUID) (Kontingen, error)
	ListCabors(ctx context.Context) ([]Cabor, error)
	ListKontingens(ctx context.Context) ([]Kontingen, error)
	ListNomorTandings(ctx context.Context) ([]NomorTanding, error)
	UpdateCabor(ctx context.Context, arg UpdateCaborParams) (Cabor, error)
	UpdateKontingen(ctx context.Context, arg UpdateKontingenParams) (Kontingen, error)
}

var _ Querier = (*Queries)(nil)
