// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID          pgtype.UUID        `json:"id"`
	ServiceName string             `json:"service_name"`
	EntityName  string             `json:"entity_name"`
	EntityID    string             `json:"entity_id"`
	Action      string             `json:"action"`
	Payload     []byte             `json:"payload"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
