// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
)

const insertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO audit_logs (service_name, entity_name, entity_id, action, payload)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, service_name, entity_name, entity_id, action, payload, created_at
`

type InsertAuditLogParams struct {
	ServiceName string `json:"service_name"`
	EntityName  string `json:"entity_name"`
	EntityID    string `json:"entity_id"`
	Action      string `json:"action"`
	Payload     []byte `json:"payload"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.ServiceName,
		arg.EntityName,
		arg.EntityID,
		arg.Action,
		arg.Payload,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.EntityName,
		&i.EntityID,
		&i.Action,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, service_name, entity_name, entity_id, action, payload, created_at FROM audit_logs
ORDER BY created_at DESC
`

func (q *Queries) ListAuditLogs(ctx context.Context) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ServiceName,
			&i.EntityName,
			&i.EntityID,
			&i.Action,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
