// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Medal struct {
	ID          pgtype.UUID        `json:"id"`
	KontingenID pgtype.UUID        `json:"kontingen_id"`
	Gold        pgtype.Int4        `json:"gold"`
	Silver      pgtype.Int4        `json:"silver"`
	Bronze      pgtype.Int4        `json:"bronze"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
