// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMedal = `-- name: AddMedal :one
INSERT INTO medals (kontingen_id, gold, silver, bronze)
VALUES ($1, $2, $3, $4)
ON CONFLICT (kontingen_id) DO UPDATE
SET 
  gold = medals.gold + EXCLUDED.gold,
  silver = medals.silver + EXCLUDED.silver,
  bronze = medals.bronze + EXCLUDED.bronze,
  updated_at = NOW()
RETURNING id, kontingen_id, gold, silver, bronze, updated_at
`

type AddMedalParams struct {
	KontingenID pgtype.UUID `json:"kontingen_id"`
	Gold        pgtype.Int4 `json:"gold"`
	Silver      pgtype.Int4 `json:"silver"`
	Bronze      pgtype.Int4 `json:"bronze"`
}

func (q *Queries) AddMedal(ctx context.Context, arg AddMedalParams) (Medal, error) {
	row := q.db.QueryRow(ctx, addMedal,
		arg.KontingenID,
		arg.Gold,
		arg.Silver,
		arg.Bronze,
	)
	var i Medal
	err := row.Scan(
		&i.ID,
		&i.KontingenID,
		&i.Gold,
		&i.Silver,
		&i.Bronze,
		&i.UpdatedAt,
	)
	return i, err
}

const getMedalStandings = `-- name: GetMedalStandings :many
SELECT id, kontingen_id, gold, silver, bronze, updated_at FROM medals
ORDER BY gold DESC, silver DESC, bronze DESC
`

func (q *Queries) GetMedalStandings(ctx context.Context) ([]Medal, error) {
	rows, err := q.db.Query(ctx, getMedalStandings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medal
	for rows.Next() {
		var i Medal
		if err := rows.Scan(
			&i.ID,
			&i.KontingenID,
			&i.Gold,
			&i.Silver,
			&i.Bronze,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
