// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateVenue(ctx context.Context, arg CreateVenueParams) (Venue, error)
	GetVenueByID(ctx context.Context, id pgtype.UUID) (Venue, error)
	ListVenues(ctx context.Context) ([]Venue, error)
	UpdateVenue(ctx context.Context, arg UpdateVenueParams) (Venue, error)
}

var _ Querier = (*Queries)(nil)
